name: code_assets
description: 商哩 SAIL LINK 电商社交平台

publish_to: 'none' # 防止意外发布到 pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^1.2.2
  shared_preferences: ^2.0.15
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  sqflite: ^2.0.3
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  amap_flutter_map: ^3.0.0
  amap_flutter_location: ^3.0.0
  # amap_search_flutter: ^3.0.0  # 暂时注释，该包在pub.dev上不存在
  flutter_slidable: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  socket_io_client: ^3.0.2
  web_socket_channel: ^2.4.0
  encrypt: ^5.0.1
  pointycastle: ^3.7.4
  # flutter_local_notifications: ^9.7.0  # 暂时注释掉，因为与flutter_driver不兼容
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  firebase_crashlytics: ^4.1.0
  flutter_markdown: ^0.7.4+3
  photo_view: ^0.15.0
  video_player: ^2.4.5
  chewie: ^1.3.4
  flutter_html: ^3.0.0-alpha.5
  webview_flutter: ^4.8.0
  flutter_stripe: ^11.5.0
  # flutter_paypal: ^0.0.8  # 暂时注释掉，因为与webview_flutter ^3.0.4版本冲突
  # flutter_alipay: ^0.1.2  # 暂时注释掉不支持空安全的包
  # wechat_pay: ^0.3.0  # 暂时注释掉不存在的包
  flutter_easyloading: ^3.0.5
  flutter_easyrefresh: ^2.2.1
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  # device_info_plus: ^4.1.2  # 暂时注释掉，因为与integration_test不兼容
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.2.7
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.0.2
  logger: ^2.5.0
  get_it: ^7.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  dartz: ^0.10.1
  rxdart: ^0.28.0
  uuid: ^4.5.1
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  # flutter_form_builder: ^7.7.0  # 暂时注释掉，因为与intl ^0.18.1版本冲突
  # form_builder_validators: ^8.3.0  # 暂时注释掉，因为依赖于flutter_form_builder
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  auto_route: ^8.1.4
  injectable: ^2.4.2
  get: ^4.6.5
  flutter_gen: ^5.9.0
  geolocator_windows: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  mockito: ^5.3.0
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  flutter_gen_runner: ^5.9.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.21.4

dependency_overrides:
  code_assets:
    git:
      url: https://github.com/finsonal/code_assets.git
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/icons/
    # - assets/animations/
    # - assets/data/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
    # - family: NotoSansSC
    #   fonts:
    #     - asset: assets/fonts/NotoSansSC-Regular.otf
    #     - asset: assets/fonts/NotoSansSC-Bold.otf
    #       weight: 700
    #     - asset: assets/fonts/NotoSansSC-Light.otf
    #       weight: 300

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
